apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-data-pv
  namespace: mysql-server
  labels:
    app: database
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /data/share
    server: 172.31.38.139
