apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data-0
  namespace: mysql-server
  labels:
    app: database
spec:
  resources:
    requests:
      storage: 1G    
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
