apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: psql-data-0
  namespace: psql-server
  labels:
    app: database
spec:
  resources:
    requests:
      storage: 1G
  storageClassName: central-data-store
  accessModes:
    - ReadWriteOnce
