apiVersion: v1
kind: Pod
metadata:
  name: with-node-affinity-with-taints
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: affinity
            operator: In
            values:
            - infra
  containers:
  - name: with-node-affinity-taint
    image: registry.k8s.io/pause:3.8