---
apiVersion: v1
kind: Namespace
metadata:
  name: hpa-test

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache
  namespace: hpa-test
spec:
  selector:
    matchLabels:
      run: php-apache
  template:
    metadata:
      labels:
        run: php-apache
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: affinity
                operator: In
                values:
                - app
      containers:
      - name: php-apache
        image: registry.k8s.io/hpa-example
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: php-apache
  namespace: hpa-test
  labels:
    run: php-apache
spec:
  ports:
  - port: 80
  selector:
    run: php-apache
