apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-svc
  namespace: mysql-server
  labels: 
    app: database
spec:
  type: ClusterIP
  selector:
    app: database
  ports:
  - port: 80
    targetPort: 80
