kind: Service
apiVersion: v1
metadata:
  name: mysql-server-svc
  namespace: mysql-server
  labels:
    app: database
spec:
  selector:
    app: database
  type: ClusterIP
  ports:
  - name: mysql-svc-port
    port: 3306
    targetPort: 3306
    