apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-data-volume
  labels:
    app: database
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: local-path